### ISSUE TITLE
Make piston dependencies optional

### ISSUE THREAD

**Issue by aepsil0n** [PistonDevelopers/cam#37]
This is in line with #36. This library is tightly coupled to how Piston does event handling and thus indirectly depends on current objects, which appear to be a bit controversial. It would be nice if one could use this library's functionality on its own.

**Comment by bvssvni** [comment]
Current objects are no longer part of the piston core.

**Comment by bvssvni** [comment]
Also, current objects are no longer as controversial as they used to be, because the safety issues with high level libraries are now solved.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/cam/pull/50.
