### ISSUE TITLE
Move `FirstPerson` to its own repo, make this library camera math only

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/cam#38]
See https://github.com/PistonDevelopers/cam/issues/36

`FirstPerson` depends on the piston core event model and it stores a `Keys` state. This library could be only for the camera math, but with methods/functions for computing everything you need to write your own controller easily.

**Comment by viperscape** [comment]
:+1:

**Comment by stjahns** [comment]
- [ ] copy first_person.rs and orbit_zoom_camera.rs into https://github.com/PistonDevelopers/camera_controllers
- [ ] switch any crates under PistonDevelopers to depend on `camera_controllers` where appropriate
- [ ] remove first_person.rs and orbit_zoom_camera.rs from cam, clean up dependencies (update dependency graph image)

**Comment by bvssvni** [comment]
This is done.
